### ISSUE TITLE
Merging Development into master (main)

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/Pyleoclim_util#320] opened 2023-02-07 23:12 UTC
According to #302, we need to eventually retire the use of main + Developpment.  Kim Pevey also points out that in 2020 Github made the transition from using a default branch for new projects of `master` over to `main`. Much of the ecosystem has followed suit by switching over existing projects. 

I propose that upon releasing 1.0.0, we simply switch the default branch to Development, using  [these instructions](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch).

**Comment by CommonClimate** [comment] 2023-02-23 17:27
Main hurdle: properly separating the environment files:
- [ ] Pyleoclim itself : https://github.com/LinkedEarth/Pyleoclim_util/pull/343.  Focus: CI
- [ ] PyleoTutorials  
- [ ] each PaleoBook repo 
- [ ] LinkedEarth Hub : union of all environments above

**Comment by khider** [comment] 2023-04-12 20:55
Development is out. I suggest that the other three tasks listed here go into their respective repos and we close this issue.

**Comment by CommonClimate** [comment] 2023-04-13 01:27
I'll get started on the PyleoTutorials this week. @alexkjames any news on CI for those?
@jordanplanders has created a brand new Hub envt, so I believe that one can be checked as done too. As for the paleobooks repos, what do you want to do?

**Comment by jordanplanders** [comment] 2023-04-13 06:06
@CommonClimate ran into an issue today pulling data via intake. Not sure what the problem is yet (one candidate is lack of pins in the environment), but will run some more tests tomorrow to try and diagnose.

**Closed** 2023-04-21 21:50 UTC
Labels: suggestions
